In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Bitcoin
The Data is downloded from [investing.com](investing.com)

In [65]:
# Loading Bitcoin Data 
df_BTC = pd.read_csv('/content/drive/MyDrive/NAICo/Data/Bitcoin Historical Data.csv')

df_BTC.head()

           Date    Price     Open     High      Low     Vol. Change %
0  May 17, 2022  30013.5  29856.7  30720.1  29804.3   74.35K    0.55%
1  May 16, 2022  29849.0  31308.3  31312.4  29135.8  100.25K   -4.66%
2  May 15, 2022  31308.7  30078.6  31383.8  29499.4   65.44K    4.08%
3  May 14, 2022  30080.4  29285.2  30277.4  28666.7   70.46K    2.72%
4  May 13, 2022  29284.4  28994.3  31002.7  28755.0  141.23K    1.06%

In [66]:
# Removing extra colmumns
df_BTC = df_BTC.drop(['Vol.', 'High', 'Low', 'Change %'], axis=1)
df_BTC = df_BTC.rename(columns={'Price': 'Close'}) 

# Change Date dtype to datetime 
df_BTC['Date'] = pd.to_datetime(df_BTC['Date'])

# New column for Rate of Return(RoR)
df_BTC['RoR'] = (df_BTC['Close'] - df_BTC['Open']) / df_BTC['Open']


df_BTC.describe()

              Close          Open          RoR
count   1827.000000   1827.000000  1827.000000
mean   18412.907772  18397.596716     0.002463
std    17659.149921  17661.516880     0.042271
min     1801.300000   1729.300000    -0.391824
25%     6584.150000   6583.600000    -0.016619
50%     9381.600000   9376.600000     0.001573
75%    33681.050000  33683.300000     0.021448
max    67527.900000  67528.700000     0.255586

In [67]:
# Searching fo any Null values
df_BTC.isnull().values.any()

False

In [68]:
# Reversing the indexing 
df_BTC = df_BTC[::-1]
df_BTC.reset_index(drop=True, inplace=True)

# Pick out data from May 17, 2017 to May 16, 2022 (5 years)
print(df_BTC['Date'][0])
print(df_BTC['Date'][len(df_BTC['Date'])-1])

# Droping the last row (Date = May 17, 2022)
df_BTC = df_BTC.drop([len(df_BTC['Date'])-1], axis=0)

df_BTC.tail()

2017-05-17 00:00:00
2022-05-17 00:00:00

           Date    Close     Open       RoR
1821 2022-05-12  28976.0  29073.4 -0.003350
1822 2022-05-13  29284.4  28994.3  0.010005
1823 2022-05-14  30080.4  29285.2  0.027154
1824 2022-05-15  31308.7  30078.6  0.040896
1825 2022-05-16  29849.0  31308.3 -0.046611

In [71]:
df_BTC.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1826 entries, 0 to 1825
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1826 non-null   datetime64[ns]
 1   Close   1826 non-null   float64
 2   Open    1826 non-null   float64
 3   RoR     1826 non-null   float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 71.3 KB

In [78]:
df_BTC.to_csv('/content/drive/MyDrive/NAICo/Cleaned Data/Bitcoin_Data.csv', index=False)

### Oil
The Data is downloded from [nasdaq.com](nasdaq.com)

In [79]:
# Loading Oil Data 
df_Oil = pd.read_csv('/content/drive/MyDrive/NAICo/Data/HistoricalData_Oil.csv')

df_Oil.head()

         Date  Close/Last  Volume    Open    High     Low
0  05/16/2022      114.20  258919  110.98  114.90  108.11
1  05/13/2022      110.49  215051  106.65  110.64  106.29
2  05/12/2022      106.13  290935  105.63  107.37  102.66
3  05/11/2022      105.71  343694   99.00  106.44   98.20
4  05/10/2022       99.76  352536  102.65  104.16   98.86

In [80]:
# Removing extra colmumns
df_Oil = df_Oil.drop(['Volume', 'High', 'Low'], axis=1)
df_Oil = df_Oil.rename(columns={'Close/Last': 'Close'}) 

# Change Date dtype to datetime 
df_Oil['Date'] = pd.to_datetime(df_Oil['Date'])

# New column for Rate of Return(RoR)
df_Oil['RoR'] = (df_Oil['Close'] - df_Oil['Open']) / df_Oil['Open']


df_Oil.describe()

             Close         Open          RoR
count  1260.000000  1260.000000  1260.000000
mean     59.486683    59.449968     0.000472
std      16.840556    16.764578     0.027418
min     -37.630000   -37.250000    -0.243875
25%      49.887500    49.815000    -0.009420
50%      58.520000    58.495000     0.001670
75%      68.110000    68.000000     0.012074
max     123.700000   124.580000     0.161972

In [81]:
# Searching fo any Null values
df_Oil.isnull().values.any()

False

In [82]:
# Reversing the indexing 
df_Oil = df_Oil[::-1]
df_Oil.reset_index(drop=True, inplace=True)

df_Oil.tail()

           Date   Close    Open       RoR
1255 2022-05-10   99.76  102.65 -0.028154
1256 2022-05-11  105.71   99.00  0.067778
1257 2022-05-12  106.13  105.63  0.004734
1258 2022-05-13  110.49  106.65  0.036006
1259 2022-05-16  114.20  110.98  0.029014

In [84]:
df_Oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1260 non-null   datetime64[ns]
 1   Close   1260 non-null   float64
 2   Open    1260 non-null   float64
 3   RoR     1260 non-null   float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 39.5 KB

In [85]:
df_Oil.to_csv('/content/drive/MyDrive/NAICo/Cleaned Data/Oil_Data.csv', index=False)

### Gold
The Data is downloded from [nasdaq.com](nasdaq.com)

In [88]:
# Loading Gold Data 
df_Gold = pd.read_csv('/content/drive/MyDrive/NAICo/Data/HistoricalData_Gold.csv')

df_Gold.head()

         Date  Close/Last    Volume    Open    High     Low
0  05/16/2022      1814.0  156521.0  1809.4  1826.0  1785.0
1  05/13/2022      1808.2  172127.0  1821.4  1827.6  1797.2
2  05/12/2022      1824.6  230455.0  1852.3  1858.8  1820.1
3  05/11/2022      1853.7  219335.0  1836.6  1857.8  1830.6
4  05/10/2022      1841.0  235122.0  1853.9  1864.7  1834.5

In [89]:
# Removing extra colmumns
df_Gold = df_Gold.drop(['Volume', 'High', 'Low'], axis=1)
df_Gold = df_Gold.rename(columns={'Close/Last': 'Close'}) 

# Change Date dtype to datetime 
df_Gold['Date'] = pd.to_datetime(df_Gold['Date'])

# New column for Rate of Return(RoR)
df_Gold['RoR'] = (df_Gold['Close'] - df_Gold['Open']) / df_Gold['Open']


df_Gold.describe()

             Close         Open          RoR
count  1260.000000  1260.000000  1260.000000
mean   1550.435794  1550.484603     0.000031
std     261.379254   261.660406     0.008578
min    1182.300000  1180.700000    -0.051943
25%    1293.700000  1294.075000    -0.003777
50%    1507.350000  1507.200000     0.000328
75%    1802.300000  1801.725000     0.004332
max    2069.400000  2076.400000     0.044205

In [90]:
# Reversing the indexing 
df_Gold = df_Gold[::-1]
df_Gold.reset_index(drop=True, inplace=True)

df_Gold.tail()

           Date   Close    Open       RoR
1255 2022-05-10  1841.0  1853.9 -0.006958
1256 2022-05-11  1853.7  1836.6  0.009311
1257 2022-05-12  1824.6  1852.3 -0.014954
1258 2022-05-13  1808.2  1821.4 -0.007247
1259 2022-05-16  1814.0  1809.4  0.002542

In [91]:
df_Gold.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1260 non-null   datetime64[ns]
 1   Close   1260 non-null   float64
 2   Open    1260 non-null   float64
 3   RoR     1260 non-null   float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 39.5 KB

In [92]:
df_Gold.to_csv('/content/drive/MyDrive/NAICo/Cleaned Data/Gold_Data.csv', index=False)